language: cpp

sudo: required

dist: trusty

compiler:
  - gcc
  - clang

before_install:
  - '.travis/before_install.sh'

script:
  - mkdir build
  - cd build
  - cmake ..
  - make -j4
  - make test

after_failure:
  - cat Testing/Temporary/LastTest.log
  - cat Testing/Temporary/LastTestsFailed.log
